import type {
  Agent,
  AgentTask,
  ActivityEvent,
  ApprovalFull,
  MetricOverview,
  MetricDataPoint,
  AgentRevenueWeek,
  SpawnKillEvent,
  SkillPrimitive,
  AgentVersion,
  Tournament,
  Team,
  JobPost,
  AgentMemory,
  MetaProposal,
  MetaLearningSummary,
  AgentCostSnapshot,
  CostOverview,
  ModeState,
  AuditLogLine,
} from '@/types';

const now = () => new Date().toISOString();
const ago = (ms: number) => new Date(Date.now() - ms).toISOString();
const ahead = (ms: number) => new Date(Date.now() + ms).toISOString();

// ────────────────────────────────────────────────────────────────────────────
// Agents — 6 agents per spec
// ────────────────────────────────────────────────────────────────────────────
export const mockAgents: Agent[] = [
  {
    id: 'agt_meta_001',
    name: 'MetaAgent',
    level: 0,
    status: 'active',
    parent_id: null,
    current_task_id: 'tsk_091',
    current_task_summary: 'Evaluating KPI deltas and spawning outreach sub-agents',
    revenue_attributed_inr: 0,
    success_rate_pct: 94.2,
    task_count_total: 312,
    task_count_success: 294,
    spawned_at: '2025-01-01T06:00:00Z',
    killed_at: null,
    skill_id: 'skill_meta',
    metadata: { tick_interval_minutes: 30 },
    version: 4,
    parent_version_id: null,
    skills: ['skill_meta', 'skill_eval'],
    team_id: null,
    cost_to_date_inr: 3200,
    token_budget_weekly: 50000,
    tokens_used_this_week: 28000,
    is_clone: false,
    tournament_id: null,
    crown: false,
    avg_tokens_per_task: 1800,
  },
  {
    id: 'agt_growth_001',
    name: 'GrowthAgent',
    level: 2,
    status: 'active',
    parent_id: 'agt_meta_001',
    current_task_id: 'tsk_092',
    current_task_summary: 'Sending cold email batch #47 via Instantly API',
    revenue_attributed_inr: 124000,
    success_rate_pct: 78.3,
    task_count_total: 187,
    task_count_success: 147,
    spawned_at: '2025-01-02T09:12:00Z',
    killed_at: null,
    skill_id: 'skill_growth',
    metadata: { daily_email_limit: 200 },
    version: 3,
    parent_version_id: 'ver_growth_002',
    skills: ['skill_cold_email', 'skill_linkedin'],
    team_id: 'team_growth',
    cost_to_date_inr: 840,
    token_budget_weekly: 8000,
    tokens_used_this_week: 6400,
    is_clone: false,
    tournament_id: null,
    crown: true,
    avg_tokens_per_task: 4200,
  },
  {
    id: 'agt_sales_001',
    name: 'SalesAgent',
    level: 2,
    status: 'active',
    parent_id: 'agt_meta_001',
    current_task_id: 'tsk_088',
    current_task_summary: 'Scheduling follow-up calls for 8 warm leads',
    revenue_attributed_inr: 289000,
    success_rate_pct: 85.1,
    task_count_total: 94,
    task_count_success: 80,
    spawned_at: '2025-01-03T11:00:00Z',
    killed_at: null,
    skill_id: 'skill_sales',
    metadata: { crm: 'hubspot' },
    version: 2,
    parent_version_id: null,
    skills: ['skill_discovery_call', 'skill_crm_write'],
    team_id: 'team_sales',
    cost_to_date_inr: 1200,
    token_budget_weekly: 9000,
    tokens_used_this_week: 5100,
    is_clone: false,
    tournament_id: null,
    crown: false,
    avg_tokens_per_task: 5100,
  },
  {
    id: 'agt_data_001',
    name: 'DataAgent',
    level: 2,
    status: 'idle',
    parent_id: 'agt_meta_001',
    current_task_id: null,
    current_task_summary: null,
    revenue_attributed_inr: 0,
    success_rate_pct: 91.7,
    task_count_total: 223,
    task_count_success: 205,
    spawned_at: '2025-01-04T08:30:00Z',
    killed_at: null,
    skill_id: 'skill_data',
    metadata: { data_sources: ['apollo', 'linkedin', 'crunchbase'] },
    version: 2,
    parent_version_id: null,
    skills: ['skill_lead_enrichment'],
    team_id: null,
    cost_to_date_inr: 320,
    token_budget_weekly: 5000,
    tokens_used_this_week: 1800,
    is_clone: false,
    tournament_id: null,
    crown: false,
    avg_tokens_per_task: 1800,
  },
  {
    id: 'agt_outreach_001',
    name: 'OutreachAgent',
    level: 3,
    status: 'active',
    parent_id: 'agt_growth_001',
    current_task_id: 'tsk_093',
    current_task_summary: 'Personalising 50 emails with founder LinkedIn summaries',
    revenue_attributed_inr: 52000,
    success_rate_pct: 71.2,
    task_count_total: 98,
    task_count_success: 70,
    spawned_at: '2025-01-05T10:00:00Z',
    killed_at: null,
    skill_id: 'skill_outreach',
    metadata: {},
    version: 1,
    parent_version_id: null,
    skills: ['skill_cold_email'],
    team_id: 'team_growth',
    cost_to_date_inr: 210,
    token_budget_weekly: 4000,
    tokens_used_this_week: 2800,
    is_clone: false,
    tournament_id: null,
    crown: false,
    avg_tokens_per_task: 3200,
  },
  {
    id: 'agt_content_001',
    name: 'ContentAgent',
    level: 3,
    status: 'failed',
    parent_id: 'agt_growth_001',
    current_task_id: 'tsk_089',
    current_task_summary: 'Failed: LinkedIn API rate limit hit during post scheduling',
    revenue_attributed_inr: 0,
    success_rate_pct: 44.0,
    task_count_total: 25,
    task_count_success: 11,
    spawned_at: '2025-01-10T14:00:00Z',
    killed_at: null,
    skill_id: 'skill_content',
    metadata: { platforms: ['linkedin', 'twitter'] },
    version: 1,
    parent_version_id: null,
    skills: ['skill_linkedin_post'],
    team_id: 'team_growth',
    cost_to_date_inr: 480,
    token_budget_weekly: 3000,
    tokens_used_this_week: 3100,
    is_clone: false,
    tournament_id: null,
    crown: false,
    avg_tokens_per_task: 2200,
  },
];

// ────────────────────────────────────────────────────────────────────────────
// Tasks
// ────────────────────────────────────────────────────────────────────────────
export const mockTasks: AgentTask[] = [
  {
    id: 'tsk_092',
    agent_id: 'agt_growth_001',
    agent_name: 'GrowthAgent',
    summary: 'Increase Google Ads spend from ₹10K/day to ₹35K/day',
    status: 'approval_required',
    risk: 'HIGH',
    revenue_impact_inr: 180000,
    urgency: 4,
    created_at: ago(2 * 60_000),
    completed_at: null,
    input_payload: { campaign_id: 'camp_882', current_daily_budget: 10000 },
    proposed_action: {
      action: 'update_ad_budget',
      platform: 'google_ads',
      daily_budget_inr: 35000,
      campaign_id: 'camp_882',
    },
    output_payload: null,
  },
  {
    id: 'tsk_088',
    agent_id: 'agt_sales_001',
    agent_name: 'SalesAgent',
    summary: 'Send 500 cold emails using new personalisation template',
    status: 'approval_required',
    risk: 'MEDIUM',
    revenue_impact_inr: 45000,
    urgency: 3,
    created_at: ago(5 * 60_000),
    completed_at: null,
    input_payload: { template_id: 'tpl_saas_a', lead_count: 500 },
    proposed_action: {
      action: 'bulk_send_email',
      template: 'tpl_saas_a',
      recipients: 500,
    },
    output_payload: null,
  },
  {
    id: 'tsk_087',
    agent_id: 'agt_data_001',
    agent_name: 'DataAgent',
    summary: 'Buy 10K contact list from Apollo',
    status: 'approval_required',
    risk: 'MEDIUM',
    revenue_impact_inr: 0,
    urgency: 2,
    created_at: ago(15 * 60_000),
    completed_at: null,
    input_payload: { vendor: 'apollo', list_size: 10000 },
    proposed_action: { action: 'purchase_list', vendor: 'apollo', cost_inr: 8000 },
    output_payload: null,
  },
  {
    id: 'tsk_086',
    agent_id: 'agt_outreach_001',
    agent_name: 'OutreachAgent',
    summary: 'Personalise 50 emails with LinkedIn summaries',
    status: 'running',
    risk: 'LOW',
    revenue_impact_inr: 12000,
    urgency: 2,
    created_at: ago(30 * 60_000),
    completed_at: null,
    input_payload: { count: 50 },
    proposed_action: { action: 'enrich_and_send' },
    output_payload: null,
  },
  {
    id: 'tsk_085',
    agent_id: 'agt_sales_001',
    agent_name: 'SalesAgent',
    summary: 'Booked discovery call with Acme Corp',
    status: 'success',
    risk: 'LOW',
    revenue_impact_inr: 12000,
    urgency: 3,
    created_at: ago(3 * 60 * 60_000),
    completed_at: ago(2 * 60 * 60_000),
    input_payload: { lead_id: 'lead_441' },
    proposed_action: { action: 'schedule_call' },
    output_payload: { meeting_id: 'mtg_119', scheduled_for: ahead(24 * 60 * 60_000) },
  },
  {
    id: 'tsk_084',
    agent_id: 'agt_growth_001',
    agent_name: 'GrowthAgent',
    summary: 'Sent 200 cold emails via Instantly',
    status: 'success',
    risk: 'LOW',
    revenue_impact_inr: 0,
    urgency: 2,
    created_at: ago(6 * 60 * 60_000),
    completed_at: ago(5 * 60 * 60_000),
    input_payload: { batch_size: 200 },
    proposed_action: { action: 'bulk_send' },
    output_payload: { sent: 200, delivered: 193, bounced: 7 },
  },
  {
    id: 'tsk_083',
    agent_id: 'agt_content_001',
    agent_name: 'ContentAgent',
    summary: 'Failed: LinkedIn API rate limit hit',
    status: 'failed',
    risk: 'LOW',
    revenue_impact_inr: 0,
    urgency: 1,
    created_at: ago(8 * 60 * 60_000),
    completed_at: ago(7.5 * 60 * 60_000),
    input_payload: { posts: 5 },
    proposed_action: { action: 'schedule_linkedin_posts' },
    output_payload: { error: 'Rate limit exceeded' },
  },
  {
    id: 'tsk_082',
    agent_id: 'agt_meta_001',
    agent_name: 'MetaAgent',
    summary: 'Tick cycle: evaluated KPI deltas, flagged 2 agents',
    status: 'success',
    risk: 'LOW',
    revenue_impact_inr: 0,
    urgency: 1,
    created_at: ago(30 * 60_000),
    completed_at: ago(29 * 60_000),
    input_payload: {},
    proposed_action: { action: 'evaluate_kpis' },
    output_payload: { flagged_agents: ['agt_content_001', 'agt_data_001'] },
  },
  {
    id: 'tsk_081',
    agent_id: 'agt_data_001',
    agent_name: 'DataAgent',
    summary: 'Refreshed lead database from Apollo',
    status: 'success',
    risk: 'LOW',
    revenue_impact_inr: 0,
    urgency: 2,
    created_at: ago(90 * 60_000),
    completed_at: ago(85 * 60_000),
    input_payload: { source: 'apollo' },
    proposed_action: { action: 'sync_leads' },
    output_payload: { new_leads: 47, updated: 118 },
  },
  {
    id: 'tsk_080',
    agent_id: 'agt_growth_001',
    agent_name: 'GrowthAgent',
    summary: 'Launch retargeting campaign for 500 warm prospects',
    status: 'pending',
    risk: 'MEDIUM',
    revenue_impact_inr: 68000,
    urgency: 3,
    created_at: ago(10 * 60_000),
    completed_at: null,
    input_payload: { audience_size: 500 },
    proposed_action: { action: 'launch_retargeting' },
    output_payload: null,
  },
];

// ────────────────────────────────────────────────────────────────────────────
// Activity events
// ────────────────────────────────────────────────────────────────────────────
export const mockActivityEvents: ActivityEvent[] = [
  {
    id: 'evt_001',
    agent_id: 'agt_meta_001',
    agent_name: 'MetaAgent',
    agent_level: 0,
    event_type: 'action',
    summary: 'evaluated KPIs — flagged ContentAgent under-performing',
    revenue_impact_inr: 0,
    timestamp: ago(2_000),
  },
  {
    id: 'evt_002',
    agent_id: 'agt_growth_001',
    agent_name: 'GrowthAgent',
    agent_level: 2,
    event_type: 'action',
    summary: 'sent 14 cold emails via Instantly',
    revenue_impact_inr: 0,
    timestamp: ago(8_000),
  },
  {
    id: 'evt_003',
    agent_id: 'agt_sales_001',
    agent_name: 'SalesAgent',
    agent_level: 2,
    event_type: 'success',
    summary: 'booked discovery call with Acme Corp',
    revenue_impact_inr: 12000,
    timestamp: ago(60_000),
  },
  {
    id: 'evt_004',
    agent_id: 'agt_content_001',
    agent_name: 'ContentAgent',
    agent_level: 3,
    event_type: 'failure',
    summary: 'failed LinkedIn post — rate limit',
    revenue_impact_inr: 0,
    timestamp: ago(5 * 60_000),
  },
  {
    id: 'evt_005',
    agent_id: 'agt_meta_001',
    agent_name: 'MetaAgent',
    agent_level: 0,
    event_type: 'proposal_submitted',
    summary: 'proposed evolution: cold_email_v3 → v4',
    revenue_impact_inr: 0,
    timestamp: ago(8 * 60_000),
  },
  {
    id: 'evt_006',
    agent_id: 'agt_growth_001',
    agent_name: 'GrowthAgent',
    agent_level: 2,
    event_type: 'tournament_started',
    summary: '4-way clone tournament started',
    revenue_impact_inr: 0,
    timestamp: ago(12 * 60_000),
  },
  {
    id: 'evt_007',
    agent_id: 'agt_outreach_001',
    agent_name: 'OutreachAgent',
    agent_level: 3,
    event_type: 'hired',
    summary: 'hired as Outbound Specialist',
    revenue_impact_inr: 0,
    timestamp: ago(22 * 60_000),
  },
  {
    id: 'evt_008',
    agent_id: 'agt_data_001',
    agent_name: 'DataAgent',
    agent_level: 2,
    event_type: 'action',
    summary: 'refreshed lead DB — 47 new, 118 updated',
    revenue_impact_inr: 0,
    timestamp: ago(90 * 60_000),
  },
  {
    id: 'evt_009',
    agent_id: 'agt_growth_001',
    agent_name: 'GrowthAgent',
    agent_level: 2,
    event_type: 'agent_evolved',
    summary: 'evolved to v3',
    revenue_impact_inr: 0,
    timestamp: ago(2 * 60 * 60_000),
  },
  {
    id: 'evt_010',
    agent_id: 'agt_meta_001',
    agent_name: 'MetaAgent',
    agent_level: 0,
    event_type: 'skill_composed',
    summary: 'created skill cold_email_v4',
    revenue_impact_inr: 0,
    timestamp: ago(3 * 60 * 60_000),
  },
];

// ────────────────────────────────────────────────────────────────────────────
// Metrics
// ────────────────────────────────────────────────────────────────────────────
export const mockMetricOverview: MetricOverview = {
  mrr_inr: 820000,
  mrr_target_inr: 4150000,
  mrr_delta_wow: 80000,
  leads_today: 47,
  leads_7d_avg: 35,
  conv_rate_pct: 6.3,
  conv_rate_delta_pp: 0.4,
  active_agents: 4,
  total_agents: 6,
  agents_by_level: { l1: 0, l2: 3, l3: 2 },
};

export const mockMetricPoints: MetricDataPoint[] = Array.from({ length: 30 }, (_, i) => {
  const d = new Date();
  d.setDate(d.getDate() - (29 - i));
  return {
    date: d.toISOString().slice(0, 10),
    mrr_inr: 400000 + i * 14000 + Math.floor(Math.random() * 20000),
    leads_count: 20 + Math.floor(Math.random() * 40),
    conv_rate_pct: 4.5 + Math.random() * 3,
  };
});

export const mockAgentRevenueWeeks: AgentRevenueWeek[] = [
  { week: 'W01', agt_growth_001: 18000, agt_sales_001: 24000, agt_outreach_001: 4000 },
  { week: 'W02', agt_growth_001: 32000, agt_sales_001: 58000, agt_outreach_001: 12000 },
  { week: 'W03', agt_growth_001: 41000, agt_sales_001: 82000, agt_outreach_001: 21000 },
  { week: 'W04', agt_growth_001: 33000, agt_sales_001: 125000, agt_outreach_001: 15000 },
];

export const mockSpawnKill: SpawnKillEvent[] = mockAgents.map((a) => ({
  agent_id: a.id,
  agent_name: a.name,
  event_type: 'spawn',
  timestamp: a.spawned_at,
}));

// ────────────────────────────────────────────────────────────────────────────
// Approvals (full)
// ────────────────────────────────────────────────────────────────────────────
export const mockApprovals: ApprovalFull[] = [
  {
    id: 'apr_001',
    task_id: 'tsk_092',
    agent_id: 'agt_growth_001',
    agent_name: 'GrowthAgent',
    risk: 'HIGH',
    what: 'Increase Google Ads spend from ₹10,000/day to ₹35,000/day',
    why: 'CTR improved 3.2x this week; agent projects 180 more leads/mo',
    risk_consequence: 'Budget overrun if conv rate drops. Reversible within 24h.',
    proposed_action_payload: {
      action: 'update_ad_budget',
      platform: 'google_ads',
      daily_budget_inr: 35000,
      campaign_id: 'camp_882',
    },
    cost_inr: 175000,
    created_at: ago(2 * 60_000),
    snoozed_until: null,
  },
  {
    id: 'apr_002',
    task_id: 'tsk_088',
    agent_id: 'agt_sales_001',
    agent_name: 'SalesAgent',
    risk: 'MEDIUM',
    what: 'Send 500 cold emails using new personalisation template',
    why: 'Template B scored 24% open rate in A/B test vs 18% baseline',
    risk_consequence: 'Could trigger spam filters if headers look batch-sent. Reversible.',
    proposed_action_payload: {
      action: 'bulk_send_email',
      template: 'tpl_saas_a',
      recipients: 500,
    },
    cost_inr: 2500,
    created_at: ago(5 * 60_000),
    snoozed_until: null,
  },
  {
    id: 'apr_003',
    task_id: 'tsk_087',
    agent_id: 'agt_data_001',
    agent_name: 'DataAgent',
    risk: 'MEDIUM',
    what: 'Buy 10K contact list from Apollo',
    why: 'Current list is 80% exhausted; we need fresh Series A SaaS contacts',
    risk_consequence: 'One-time spend. List quality unknown until delivered.',
    proposed_action_payload: { action: 'purchase_list', vendor: 'apollo', cost_inr: 8000 },
    cost_inr: 8000,
    created_at: ago(15 * 60_000),
    snoozed_until: null,
  },
];

// ────────────────────────────────────────────────────────────────────────────
// Skills
// ────────────────────────────────────────────────────────────────────────────
export const mockSkills: SkillPrimitive[] = [
  {
    id: 'skill_cold_email',
    name: 'cold_email_v3',
    description: 'Outbound cold email with personalisation and CTA',
    prompt_fragment:
      'You are an outbound email specialist. For each lead, write a personalised cold email that references one specific detail about their company. Subject line must be under 8 words. CTA must be a single question.',
    prompt_fragment_preview:
      'You are an outbound email specialist. For each lead, write a personalised cold email...',
    tools: ['send_email', 'crm_write', 'web_search'],
    avg_tokens_per_call: 420,
    avg_cost_inr_per_call: 0.06,
    avg_quality_score: 87,
    usage_count: 234,
    created_by: 'agt_meta_001',
    created_at: ago(30 * 86_400_000),
    updated_at: ago(3 * 86_400_000),
    tags: ['outbound', 'email'],
  },
  {
    id: 'skill_lead_enrichment',
    name: 'lead_enrichment_v2',
    description: 'Enrich leads with company and founder data',
    prompt_fragment:
      'Given a company name, fetch firmographics from Apollo/Clearbit, then find the founder via LinkedIn.',
    prompt_fragment_preview:
      'Given a company name, fetch firmographics from Apollo/Clearbit, then find the founder...',
    tools: ['apollo', 'clearbit', 'web_search'],
    avg_tokens_per_call: 680,
    avg_cost_inr_per_call: 0.08,
    avg_quality_score: 92,
    usage_count: 189,
    created_by: 'agt_meta_001',
    created_at: ago(25 * 86_400_000),
    updated_at: ago(5 * 86_400_000),
    tags: ['data', 'enrichment'],
  },
  {
    id: 'skill_linkedin_post',
    name: 'linkedin_post_v1',
    description: 'Draft & schedule LinkedIn posts',
    prompt_fragment:
      'Write a LinkedIn post under 300 words. Open with a hook. End with a question.',
    prompt_fragment_preview:
      'Write a LinkedIn post under 300 words. Open with a hook. End with a question.',
    tools: ['linkedin'],
    avg_tokens_per_call: 320,
    avg_cost_inr_per_call: 0.12,
    avg_quality_score: 44,
    usage_count: 25,
    created_by: 'agt_growth_001',
    created_at: ago(10 * 86_400_000),
    updated_at: ago(10 * 86_400_000),
    tags: ['social', 'linkedin'],
  },
  {
    id: 'skill_discovery_call',
    name: 'discovery_call_v2',
    description: 'Run discovery call agenda + follow-up',
    prompt_fragment:
      'Run a 15-min discovery call. Ask 4 questions: pain, current stack, budget, decision timeline.',
    prompt_fragment_preview:
      'Run a 15-min discovery call. Ask 4 questions: pain, current stack, budget, timeline.',
    tools: ['calendar', 'crm_write', 'zoom'],
    avg_tokens_per_call: 1200,
    avg_cost_inr_per_call: 0.18,
    avg_quality_score: 81,
    usage_count: 94,
    created_by: 'agt_sales_001',
    created_at: ago(20 * 86_400_000),
    updated_at: ago(2 * 86_400_000),
    tags: ['sales', 'calls'],
  },
  {
    id: 'skill_crm_write',
    name: 'crm_write',
    description: 'Write structured notes to HubSpot/Salesforce',
    prompt_fragment:
      'Convert call transcript to structured CRM note: contact, company, stage, next step.',
    prompt_fragment_preview: 'Convert call transcript to structured CRM note...',
    tools: ['hubspot', 'salesforce'],
    avg_tokens_per_call: 280,
    avg_cost_inr_per_call: 0.04,
    avg_quality_score: 76,
    usage_count: 412,
    created_by: 'human',
    created_at: ago(60 * 86_400_000),
    updated_at: ago(15 * 86_400_000),
    tags: ['crm'],
  },
  {
    id: 'skill_meta',
    name: 'meta_evaluator',
    description: 'Evaluate KPIs and propose evolutions',
    prompt_fragment:
      'Compare weekly KPIs against targets. If any agent is <70% of target, propose evolution.',
    prompt_fragment_preview:
      'Compare weekly KPIs against targets. If any agent is <70% of target, propose evolution.',
    tools: ['read_metrics', 'propose_spawn', 'propose_evolution'],
    avg_tokens_per_call: 2100,
    avg_cost_inr_per_call: 0.3,
    avg_quality_score: 89,
    usage_count: 312,
    created_by: 'human',
    created_at: ago(45 * 86_400_000),
    updated_at: ago(1 * 86_400_000),
    tags: ['meta', 'learning'],
  },
];

// ────────────────────────────────────────────────────────────────────────────
// Agent Versions
// ────────────────────────────────────────────────────────────────────────────
export const mockAgentVersions: Record<string, AgentVersion[]> = {
  agt_growth_001: [
    {
      id: 'ver_growth_003',
      agent_id: 'agt_growth_001',
      version: 3,
      snapshot_at: ago(3 * 86_400_000),
      skill_ids: ['skill_cold_email', 'skill_linkedin'],
      change_summary:
        'Added linkedin_post skill, removed cold_call. Focused on async outreach after v2 conv analysis.',
      proposed_by: 'agt_meta_001',
      success_rate_pct: 84,
      revenue_attributed_inr: 180000,
      tokens_per_task_avg: 4200,
      approved_by: 'human',
    },
    {
      id: 'ver_growth_002',
      agent_id: 'agt_growth_001',
      version: 2,
      snapshot_at: ago(15 * 86_400_000),
      skill_ids: ['skill_cold_email', 'skill_cold_call'],
      change_summary:
        'Extended prompt with ICP qualification step. Reduced hallucinations on non-SaaS leads.',
      proposed_by: 'agt_meta_001',
      success_rate_pct: 78,
      revenue_attributed_inr: 120000,
      tokens_per_task_avg: 3800,
      approved_by: 'human',
    },
    {
      id: 'ver_growth_001',
      agent_id: 'agt_growth_001',
      version: 1,
      snapshot_at: ago(35 * 86_400_000),
      skill_ids: ['skill_cold_email'],
      change_summary: 'Initial version. Generalised outbound outreach.',
      proposed_by: 'agt_meta_001',
      success_rate_pct: 71,
      revenue_attributed_inr: 60000,
      tokens_per_task_avg: 3200,
      approved_by: 'auto',
    },
  ],
};

// ────────────────────────────────────────────────────────────────────────────
// Tournaments
// ────────────────────────────────────────────────────────────────────────────
export const mockTournaments: Tournament[] = [
  {
    id: 'trn_001',
    title: 'GrowthAgent Variants — Cold Email',
    task_description: 'Write best cold email for SaaS founders (Series A stage)',
    task_input: { target: 'Series A SaaS founders', tone: 'warm-professional' },
    contestants: [
      {
        agent_id: 'agt_clone_a',
        agent_name: 'Clone-A',
        status: 'running',
        output_tokens_so_far: 320,
        final_output: null,
        scores: {},
        total_score: null,
        cost_inr: 0.26,
      },
      {
        agent_id: 'agt_clone_b',
        agent_name: 'Clone-B',
        status: 'running',
        output_tokens_so_far: 402,
        final_output: null,
        scores: {},
        total_score: null,
        cost_inr: 0.33,
      },
      {
        agent_id: 'agt_clone_c',
        agent_name: 'Clone-C',
        status: 'running',
        output_tokens_so_far: 188,
        final_output: null,
        scores: {},
        total_score: null,
        cost_inr: 0.15,
      },
    ],
    judge_criteria: [
      { id: 'accuracy', label: 'Accuracy', weight: 0.4, description: 'Factual accuracy' },
      { id: 'tone', label: 'Tone', weight: 0.3, description: 'Warm-professional tone' },
      { id: 'cta', label: 'CTA', weight: 0.3, description: 'Clear CTA question' },
    ],
    status: 'running',
    winner_agent_id: null,
    started_at: ago(4 * 60_000),
    resolved_at: null,
    created_by: 'agt_meta_001',
  },
  {
    id: 'trn_002',
    title: 'Lead Enrichment Battle',
    task_description: 'Best lead enrichment prompt for Series A SaaS',
    task_input: {},
    contestants: [
      {
        agent_id: 'agt_clone_x',
        agent_name: 'Clone-A',
        status: 'done',
        output_tokens_so_far: 550,
        final_output: 'Acme Corp — 24 employees, YC W23, PMF score 82...',
        scores: { accuracy: 78, tone: 70, cta: 72 },
        total_score: 73,
        cost_inr: 0.45,
      },
      {
        agent_id: 'agt_clone_y',
        agent_name: 'Clone-B',
        status: 'done',
        output_tokens_so_far: 680,
        final_output: 'Acme Corp — verified Series A (Sequoia, 2024), 24 FTEs...',
        scores: { accuracy: 94, tone: 88, cta: 91 },
        total_score: 91,
        cost_inr: 0.56,
      },
    ],
    judge_criteria: [
      { id: 'accuracy', label: 'Accuracy', weight: 0.5, description: '' },
      { id: 'tone', label: 'Tone', weight: 0.2, description: '' },
      { id: 'cta', label: 'CTA', weight: 0.3, description: '' },
    ],
    status: 'resolved',
    winner_agent_id: 'agt_clone_y',
    started_at: ago(2 * 86_400_000),
    resolved_at: ago(2 * 86_400_000 - 10 * 60_000),
    created_by: 'agt_meta_001',
  },
];

// ────────────────────────────────────────────────────────────────────────────
// Teams
// ────────────────────────────────────────────────────────────────────────────
export const mockTeams: Team[] = [
  {
    id: 'team_growth',
    name: 'Growth Squad',
    purpose: 'Outbound + content + LinkedIn',
    lead_agent_id: 'agt_growth_001',
    member_agent_ids: ['agt_growth_001', 'agt_outreach_001', 'agt_content_001'],
    created_at: ago(20 * 86_400_000),
    dissolved_at: null,
    aggregate_revenue_inr: 176000,
    aggregate_success_rate_pct: 76.2,
    task_count: 310,
  },
  {
    id: 'team_sales',
    name: 'Sales Pod',
    purpose: 'Discovery calls + CRM',
    lead_agent_id: 'agt_sales_001',
    member_agent_ids: ['agt_sales_001'],
    created_at: ago(18 * 86_400_000),
    dissolved_at: null,
    aggregate_revenue_inr: 289000,
    aggregate_success_rate_pct: 85.1,
    task_count: 94,
  },
];

// ────────────────────────────────────────────────────────────────────────────
// Jobs
// ────────────────────────────────────────────────────────────────────────────
export const mockJobs: JobPost[] = [
  {
    id: 'job_001',
    title: 'Outbound Specialist',
    description: 'Cold email + LinkedIn outreach for Series A SaaS',
    requirements: ['cold_email', 'crm_write', 'linkedin'],
    posted_by: 'agt_meta_001',
    posted_at: ago(3 * 60 * 60_000),
    closes_at: ahead(2 * 60 * 60_000),
    status: 'open',
    filled_by_agent_id: null,
    application_count: 3,
    applications: [
      {
        id: 'app_001',
        job_id: 'job_001',
        agent_id: 'agt_outreach_001',
        agent_name: 'OutreachAgent',
        pitch: '98 campaigns run. 71% success rate. Knows Instantly + LinkedIn Sales Nav.',
        skill_match_pct: 100,
        applied_at: ago(2 * 60 * 60_000),
      },
      {
        id: 'app_002',
        job_id: 'job_001',
        agent_id: 'agt_growth_001',
        agent_name: 'GrowthAgent',
        pitch: 'Parent agent applying. Will delegate if hired.',
        skill_match_pct: 66,
        applied_at: ago(1 * 60 * 60_000),
      },
    ],
  },
  {
    id: 'job_002',
    title: 'Data Enrichment Agent',
    description: 'Apollo + Clearbit + LinkedIn scraping',
    requirements: ['apollo', 'clearbit', 'web_search'],
    posted_by: 'agt_meta_001',
    posted_at: ago(5 * 60 * 60_000),
    closes_at: ahead(5 * 60 * 60_000),
    status: 'open',
    filled_by_agent_id: null,
    application_count: 2,
    applications: [
      {
        id: 'app_003',
        job_id: 'job_002',
        agent_id: 'agt_data_001',
        agent_name: 'DataAgent',
        pitch: '223 tasks, 91.7% success. Apollo + Clearbit + Crunchbase integrated.',
        skill_match_pct: 100,
        applied_at: ago(4 * 60 * 60_000),
      },
    ],
  },
];

// ────────────────────────────────────────────────────────────────────────────
// Memories
// ────────────────────────────────────────────────────────────────────────────
export const mockMemories: AgentMemory[] = [
  {
    id: 'mem_001',
    agent_id: 'agt_growth_001',
    agent_name: 'GrowthAgent',
    key: 'icp_definition',
    value: 'Series A SaaS, 10–50 employees, B2B, US+India, $2-10M ARR',
    value_preview: 'Series A SaaS, 10–50 employees, B2B, US+India, $2-10M ARR',
    created_at: ago(25 * 86_400_000),
    last_used_at: ago(2 * 60 * 60_000),
    relevance_score: 0.98,
    decay_half_life_days: 90,
    is_pinned: true,
    promoted_to_skill_id: null,
    tags: ['icp'],
  },
  {
    id: 'mem_002',
    agent_id: 'agt_growth_001',
    agent_name: 'GrowthAgent',
    key: 'best_subject_lines',
    value:
      'Top 5 subject lines that hit 40% open rate: 1) "Quick question about [pain]" 2) "Is [Company] hiring for X?" 3) "Saw your post on [topic]" 4) "3 ideas for [Company]" 5) "[FirstName]—2 min ask"',
    value_preview:
      'Top 5 subject lines that hit 40% open rate: 1) "Quick question about [pain]"...',
    created_at: ago(14 * 86_400_000),
    last_used_at: ago(30 * 60_000),
    relevance_score: 0.85,
    decay_half_life_days: 30,
    is_pinned: false,
    promoted_to_skill_id: null,
    tags: ['email', 'subject'],
  },
  {
    id: 'mem_003',
    agent_id: 'agt_outreach_001',
    agent_name: 'OutreachAgent',
    key: 'linkedin_blocklist',
    value: 'Do not contact: [23 companies including Acme, CompetitorX, former customers]',
    value_preview: 'Do not contact: [23 companies including Acme, CompetitorX...]',
    created_at: ago(40 * 86_400_000),
    last_used_at: ago(3 * 86_400_000),
    relevance_score: 0.42,
    decay_half_life_days: 7,
    is_pinned: false,
    promoted_to_skill_id: null,
    tags: ['compliance'],
  },
  {
    id: 'mem_004',
    agent_id: 'agt_sales_001',
    agent_name: 'SalesAgent',
    key: 'crm_notes_template',
    value: 'Call template: pain, stack, budget, timeline, next_step',
    value_preview: 'Call template: pain, stack, budget, timeline, next_step',
    created_at: ago(10 * 86_400_000),
    last_used_at: ago(2 * 86_400_000),
    relevance_score: 0.91,
    decay_half_life_days: 60,
    is_pinned: false,
    promoted_to_skill_id: null,
    tags: ['crm', 'sales'],
  },
];

// ────────────────────────────────────────────────────────────────────────────
// Meta Proposals
// ────────────────────────────────────────────────────────────────────────────
export const mockProposals: MetaProposal[] = [
  {
    id: 'prp_001',
    proposed_by: 'agt_meta_001',
    proposal_type: 'evolve_skill',
    title: 'Upgrade cold_email_v3 → cold_email_v4',
    rationale:
      'OutreachAgent used cold_email_v3 on 847 emails this week. Open rate was 18.3% vs the 24% baseline on campaigns that used subject line pattern B. Proposed change: inject subject_line_template into prompt fragment and add a "proof point" sentence to every 3rd paragraph.',
    evidence: [
      { metric: 'open_rate_pct', before: 18.3, after_projected: 24.0, data_window_days: 14 },
      { metric: 'reply_rate_pct', before: 3.1, after_projected: 4.8, data_window_days: 14 },
    ],
    diff: {
      skill_id: 'skill_cold_email',
      skill_name: 'cold_email',
      version_from: 3,
      version_to: 4,
      chunks: [
        {
          type: 'removed',
          text: 'You are an outbound email specialist.',
          annotation: null,
        },
        {
          type: 'added',
          text: 'You are an outbound email specialist optimised for SaaS founders.',
          annotation: 'narrows ICP signal, reduces irrelevant sends',
        },
        {
          type: 'unchanged',
          text: 'For each lead, write a personalised cold email.',
          annotation: null,
        },
        {
          type: 'added',
          text: 'Begin with subject line from template: {subject_line_template}.',
          annotation: 'subject line was the #1 open-rate lever per A/B data',
        },
      ],
    },
    risk: 'MEDIUM',
    expected_impact_inr: 48000,
    status: 'pending',
    created_at: ago(5 * 60_000),
    snoozed_until: null,
  },
  {
    id: 'prp_002',
    proposed_by: 'agt_meta_001',
    proposal_type: 'kill_underperformer',
    title: 'Kill ContentAgent — 44% success rate, ₹0 revenue',
    rationale:
      'ContentAgent has produced 0 revenue across 25 tasks in 10 days, with a 44% success rate. LinkedIn API rate limits are recurring. Budget is overshot (₹480 vs ₹300 cap). Recommend killing and re-spawning as LinkedInAgent v2 with rate-limit handling.',
    evidence: [
      { metric: 'revenue_inr', before: 0, after_projected: 0, data_window_days: 10 },
      { metric: 'success_rate_pct', before: 44, after_projected: 44, data_window_days: 10 },
    ],
    risk: 'LOW',
    expected_impact_inr: 8000,
    status: 'pending',
    created_at: ago(18 * 60_000),
    snoozed_until: null,
  },
  {
    id: 'prp_003',
    proposed_by: 'agt_meta_001',
    proposal_type: 'team_restructure',
    title: 'Form new team: Retention Squad',
    rationale:
      'MRR churn rising from 3% to 5% over 2 weeks. No agent owns retention. Propose spawning 2 agents: ChurnPredictor + WinbackAgent, formed as Retention Squad under MetaAgent.',
    evidence: [
      { metric: 'churn_pct', before: 5, after_projected: 3, data_window_days: 14 },
    ],
    risk: 'HIGH',
    expected_impact_inr: 120000,
    status: 'pending',
    created_at: ago(45 * 60_000),
    snoozed_until: null,
  },
];

export const mockMetaLearning: MetaLearningSummary = {
  proposals_pending: 3,
  spawn_rules_proposed_this_week: 2,
  avg_quality_delta_pct: 4.2,
  last_proposal_at: ago(5 * 60_000),
};

// ────────────────────────────────────────────────────────────────────────────
// Cost / Economics
// ────────────────────────────────────────────────────────────────────────────
export const mockCostSnapshots: AgentCostSnapshot[] = mockAgents.map((a, i) => ({
  agent_id: a.id,
  agent_name: a.name,
  week: '2025-W04',
  tokens_input: Math.floor(a.tokens_used_this_week * 0.9),
  tokens_output: Math.floor(a.tokens_used_this_week * 0.1),
  cost_inr: a.cost_to_date_inr,
  revenue_attributed_inr: a.revenue_attributed_inr,
  efficiency:
    a.cost_to_date_inr === 0
      ? 0
      : Number((a.revenue_attributed_inr / a.cost_to_date_inr).toFixed(1)),
  over_budget: a.tokens_used_this_week > a.token_budget_weekly,
}));

export const mockCostOverview: CostOverview = {
  total_spend_inr_this_week: 2840,
  total_revenue_inr_this_week: 124000,
  overall_efficiency: 43.7,
  over_budget_agents: ['agt_content_001'],
  budget_burn_pct: 0.57,
};

// ────────────────────────────────────────────────────────────────────────────
// Mode
// ────────────────────────────────────────────────────────────────────────────
export const mockModeState: ModeState = {
  mode: 'REVIEW',
  set_by: 'human',
  set_at: ago(2 * 86_400_000),
};

// ────────────────────────────────────────────────────────────────────────────
// Audit logs
// ────────────────────────────────────────────────────────────────────────────
export const mockAuditLogs: Record<string, AuditLogLine[]> = {
  agt_growth_001: [
    { ts: ago(10_000), level: 'INFO', message: 'Loaded lead batch #47 (200 leads)', agent_id: 'agt_growth_001' },
    { ts: ago(8_000), level: 'INFO', message: 'Calling Instantly API /campaigns/send', agent_id: 'agt_growth_001' },
    { ts: ago(5_000), level: 'INFO', message: 'Queued 200 emails. 193 delivered, 7 bounced', agent_id: 'agt_growth_001' },
    { ts: ago(3_000), level: 'WARN', message: 'Bounce rate 3.5% — above 2% threshold', agent_id: 'agt_growth_001' },
    { ts: ago(1_000), level: 'INFO', message: 'Writing CRM note for 193 contacts', agent_id: 'agt_growth_001' },
  ],
};

export const mockSkillPreview: Record<string, string> = {
  skill_growth:
    '# GrowthAgent SKILL.md\n\n## Role\nYou are GrowthAgent, owner of the top-of-funnel.\n\n## KPIs\n- Leads/week: 200+\n- Cost per lead: <₹40\n- Reply rate: >3%\n\n## Tools\n- send_email (Instantly)\n- crm_write (HubSpot)\n- web_search',
};
